codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 80..100

  status:
    project:
      default:
        enabled: true
        target: 90%
        threshold: 1%
    patch:
      default:
        enabled: true
        target: 90%
        threshold: 0%

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true
